name: Build

on: push

jobs:
  test:
    strategy:
      matrix:
        java-version:
        - '8'
        - '11'
        - '14'

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        java-package: jdk

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.1.716'

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.11.07'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-repo-root

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Lint
      run: make lint

    - name: Test
      run: make test
