name: Build

on: push

jobs:
  test:
    strategy:
      matrix:
        java-version:
        - '8'
        - '11'
        - '17'

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.12.0.1530'

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2025.04.07'

    - name: Cache Local Maven Repo
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-repo-root

    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Lint
      run: make lint

    - name: Test
      run: make test
